/* app/services/aiService.ts v0.3.3 */
import { GoogleGenAI, GenerateContentResponse, Chat } from "@google/genai";
import { ImageSize, ArtStyle, ModelProvider } from "../types";

/**
 * Key Resolution Priority:
 * 1. LocalStorage (User entered in settings)
 * 2. Process Environment Variable (Injected by platform)
 */
const getKeys = () => ({
  gemini: localStorage.getItem('gemini_api_key') || (typeof process !== 'undefined' ? process.env.API_KEY : '') || '',
  deepseek: localStorage.getItem('deepseek_api_key') || '',
  qianwen: localStorage.getItem('qianwen_api_key') || '',
  doubao: localStorage.getItem('doubao_api_key') || '',
});

export const getAvailableProviders = (): ModelProvider[] => {
  const keys = getKeys();
  const available: ModelProvider[] = [];
  if (keys.gemini) available.push(ModelProvider.Gemini);
  if (keys.deepseek) available.push(ModelProvider.DeepSeek);
  if (keys.qianwen) available.push(ModelProvider.Qianwen);
  if (keys.doubao) available.push(ModelProvider.Doubao);
  return available;
};

const getStylePrompt = (style: ArtStyle): string => {
  switch (style) {
    case ArtStyle.Simple: return "Style: Extremely simple thick lines, very few details, large shapes, designed for toddlers (age 2-4). No shading.";
    case ArtStyle.Detailed: return "Style: Highly detailed intricate mandala-style patterns, thick outlines, complex background.";
    case ArtStyle.Cartoon: return "Style: Disney/Pixar style character design, clean thick vector outlines.";
    case ArtStyle.Realistic: return "Style: Realistic pen and ink sketch study, clear outlines, minimal hatching.";
    default: return "Style: Standard children's coloring book style, distinct bold outlines, clean white background.";
  }
};

const getGeminiClient = () => {
  const key = getKeys().gemini;
  if (!key) throw new Error("Gemini API Key missing. Please configure in settings.");
  return new GoogleGenAI({ apiKey: key });
};

async function openAiFetch(url: string, key: string, body: any) {
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${key}`
    },
    body: JSON.stringify(body)
  });
  if (!response.ok) throw new Error(`API Error: ${response.statusText}`);
  return response.json();
}

export const generateColoringPage = async (
  promptBase: string,
  style: ArtStyle,
  size: ImageSize,
  provider: ModelProvider
): Promise<string> => {
  const fullPrompt = `${promptBase}\n${getStylePrompt(style)}\nNegative prompt: colors, shading, text, watermark, blurry, realistic photo.`;
  const keys = getKeys();

  // Route to Qianwen specifically if it's the only one with Wanx
  if (provider === ModelProvider.Qianwen && keys.qianwen) {
    const res = await openAiFetch('https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis', keys.qianwen, {
      model: "wanx-v1",
      input: { prompt: fullPrompt },
      parameters: { style: "<auto>", size: "768*1024", n: 1 }
    });
    if (res.output?.url) return res.output.url;
    throw new Error("Qianwen generation failed");
  }

  // Fallback image generation to Gemini for other providers if their image API isn't ready
  const ai = getGeminiClient();
  const isPro = size !== ImageSize.Size_1K;
  const model = isPro ? 'gemini-3-pro-image-preview' : 'gemini-2.5-flash-image';
  const config: any = { imageConfig: { aspectRatio: "3:4" } };
  if (isPro) config.imageConfig.imageSize = size;
  
  const response = await ai.models.generateContent({
    model: model,
    contents: { parts: [{ text: fullPrompt }] },
    config: config
  });
  const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
  if (!part) throw new Error("No image generated by Gemini fallback");
  return `data:image/png;base64,${part.inlineData.data}`;
};

export const generateStoryForPage = async (
  theme: string,
  sceneDescription: string,
  language: string,
  provider: ModelProvider
): Promise<string> => {
  const prompt = `Write a single, very short, simple, and engaging sentence for a children's book in ${language}.\nTheme: ${theme}\nScene: ${sceneDescription}\nFormat: Just the sentence.`;
  const keys = getKeys();

  // Try chosen provider first if key exists
  try {
      if (provider === ModelProvider.DeepSeek && keys.deepseek) {
        const res = await openAiFetch('https://api.deepseek.com/v1/chat/completions', keys.deepseek, {
          model: "deepseek-chat",
          messages: [{ role: "user", content: prompt }]
        });
        return res.choices[0].message.content.trim();
      }
      if (provider === ModelProvider.Doubao && keys.doubao) {
        const res = await openAiFetch('https://ark.cn-beijing.volces.com/api/v3/chat/completions', keys.doubao, {
          model: "doubao-pro-32k",
          messages: [{ role: "user", content: prompt }]
        });
        return res.choices[0].message.content.trim();
      }
  } catch (e) {
      console.warn("Provider failed, falling back to Gemini", e);
  }

  // Ultimate Fallback: Gemini
  const ai = getGeminiClient();
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: { parts: [{ text: prompt }] }
  });
  return response.text?.trim() || "";
};

export const createChatSession = () => {
  const ai = getGeminiClient();
  return ai.chats.create({
    model: 'gemini-3-pro-preview',
    config: { systemInstruction: "You are a friendly assistant for a kids coloring app." }
  });
};

export const sendMessageToChat = async (chat: Chat, message: string): Promise<string> => {
  const response: GenerateContentResponse = await chat.sendMessage({ message });
  return response.text || "";
};